### ISSUE TITLE
Wrong tokenizer path in big model config

### ISSUE THREAD

**Issue by RomanCast** [bigscience-workshop/bigscience#32]
Hello,

The final model config seems to be pointing toward the wrong tokenizer : 

https://github.com/bigscience-workshop/bigscience/blob/155dd126b0dd531a2da07c9970bd10f7e8843b7c/train/tr11-176B-ml/tr11-176B-ml.slurm#L117

@thomasw21 notified me this one was used for testing purpose only since there is already an existing dataset tokenized with this tokenizer. 

This issue tracks the fact that in a later stage this should be changed to : 

`     --tokenizer-name-or-path bigscience-catalogue-data-dev/byte-level-bpe-tokenizer-no-norm-250k-whitespace-and-eos-regex-alpha-v3-dedup-lines-articles \ `

@stas00

**Comment by stas00** [comment]
@thomasw21 says it's not ready yet to be switched over, so please coordinate it first and when ready we will switch over to it.
